// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6IS3WDHiaOnx6rlaQfFp-jxL81XwBdU',
    appId: '1:951365338084:web:b52256a226d3f662067df1',
    messagingSenderId: '951365338084',
    projectId: 'useai-414821',
    authDomain: 'useai-414821.firebaseapp.com',
    storageBucket: 'useai-414821.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3yW1A299JbZyKSsl7Kq6n8T-EuC4pCo',
    appId: '1:951365338084:android:db467d8eefba6b84067df1',
    messagingSenderId: '951365338084',
    projectId: 'useai-414821',
    storageBucket: 'useai-414821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKBEp1aBmmKDTyK8MJ7aEmoLKIhF6yGDE',
    appId: '1:951365338084:ios:7ef3cf7f56091727067df1',
    messagingSenderId: '951365338084',
    projectId: 'useai-414821',
    storageBucket: 'useai-414821.appspot.com',
    iosBundleId: 'com.codeaijourney.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKBEp1aBmmKDTyK8MJ7aEmoLKIhF6yGDE',
    appId: '1:951365338084:ios:7ef3cf7f56091727067df1',
    messagingSenderId: '951365338084',
    projectId: 'useai-414821',
    storageBucket: 'useai-414821.appspot.com',
    iosBundleId: 'com.codeaijourney.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw6IS3WDHiaOnx6rlaQfFp-jxL81XwBdU',
    appId: '1:951365338084:web:320dcdd849459925067df1',
    messagingSenderId: '951365338084',
    projectId: 'useai-414821',
    authDomain: 'useai-414821.firebaseapp.com',
    storageBucket: 'useai-414821.appspot.com',
  );

}